version: 2
github_models:
  - gpt-4
  - gpt-3.5-turbo
copilot:
  enable_auto_completions: true
  enable_suggestions: true
  enable_chat: true
# Updated Sun Nov  9 12:50:31 CET 2025
# Updated Sun Nov  9 12:52:07 CET 2025
