extends: default

rules:
  line-length:
    max: 120
  comments:
    min-spaces-from-content: 1
  document-start: disable
  truthy:
    allowed-values: ['true', 'false', 'on', 'off']# Updated Sun Nov  9 12:50:30 CET 2025
# Updated Sun Nov  9 12:52:07 CET 2025
