name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

env:
  TF_VERSION: 1.5.0
  AWS_REGION: eu-central-1

jobs:
  terraform-validate:
    name: Terraform Validate
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ env.TF_VERSION }}
    
    - name: Terraform Format Check
      run: terraform fmt -check -recursive
      working-directory: terraform
    
    - name: Terraform Init
      run: terraform init -backend=false
      working-directory: terraform
    
    - name: Terraform Validate
      run: terraform validate
      working-directory: terraform

  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'
        format: 'sarif'
        output: 'trivy-results.sarif'
    
    - name: Upload Trivy scan results
      uses: github/codeql-action/upload-sarif@v3
      if: always()
      with:
        sarif_file: 'trivy-results.sarif'

  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    needs: [terraform-validate]
    if: github.event_name == 'pull_request' && false  # Disabled - requires AWS credentials
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ env.TF_VERSION }}
    
    - name: Terraform Init
      run: terraform init -backend=false
      working-directory: terraform
    
    - name: Terraform Plan (Dry Run)
      run: terraform plan -var-file="environments/dev/terraform.tfvars" -no-color
      working-directory: terraform

  docs-check:
    name: Documentation Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Check for README updates
      run: |
        if [ -f README.md ]; then
          echo "README.md exists"
        else
          echo "README.md missing"
          exit 1
        fi
    
    - name: Lint Markdown
      uses: DavidAnson/markdownlint-cli2-action@v14
      with:
        globs: '**/*.md'