name: Terraform CI/CD

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  terraform-validation:
    name: Terraform Validation
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.5.0
    
    - name: Terraform Init
      run: terraform init -backend=false
      working-directory: terraform
    
    - name: Terraform Validate
      run: terraform validate
      working-directory: terraform

  code-quality:
    name: Code Quality
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Check file structure
      run: |
        echo "Checking project structure..."
        [ -d terraform ] && echo "✓ terraform/ directory found"
        [ -d scripts ] && echo "✓ scripts/ directory found"
        [ -d examples ] && echo "✓ examples/ directory found"
        echo "Structure check completed"